### ISSUE TITLE
Create reaktor gem

### ISSUE THREAD

**Issue by rnelson0** [pzim/reaktor#12]
Create an installable gem so that users do not need to clone the repo. This will ease the ability to create a puppet module to maintain reaktor itself, plus make manual upgrades a little smoother.

**Comment by pzim** [comment]
Hi @rnelson0 - is this still something you are considering? If not, I'll close this out. Thanks!

**Comment by rnelson0** [comment]
@pzim Being realistic, no - and if it is, I'll open a new ticket when I actually start working on something. I'll close it out, thanks!
