### ISSUE TITLE
Does it work with simple gitolite?

### ISSUE THREAD

**Issue by dhajoshi** [pzim/reaktor#21]
Hello,

can i make it to work with simple gitolite?

Regards,
DJ

**Comment by pzim** [comment]
Hi,

I haven't tried using reaktor with gitolite, however it may work using the
gitlab or stash endpoint. I believe they are generic enough to work. If you
find that it does not work as expected, feel free to open an issue or
submit a PR.

Phil

**Comment by pzim** [comment]
Hi @dhajoshi - have you been able to verify reaktor works with gitolite?

**Comment by dhajoshi** [comment]
Hey, not yet, will try if i will get chance, and let you know.

**Comment by pzim** [comment]
Hi @dhajoshi, I'll plan on closing out this issue soon unless it's still relevant. Let me know.

**Comment by dhajoshi** [comment]
Sorry sir, yes please close this one, i am still investigating my work flow
and will move to gitlab once decided.
