### ISSUE TITLE
support gitlab 

### ISSUE THREAD

**Issue by logicminds** [pzim/reaktor#23]
Gitlab is used anywhere there is a lock down environment.  It would be nice to have gitlab support built in.  There are a few ruby gems that integrate with the gitlab web api already, so this should be somewhat trial.

**Comment by tremblaysimon** [comment]
There is a support for gitlab.

**Comment by pzim** [comment]
Yes, reaktor works with gitlab. Is there some kind of functionality you're
not seeing?

**Comment by logicminds** [comment]
I never used it because the docs only mentioned github.

**Comment by pzim** [comment]
A bug in the docs then possibly. I'll take a look soon and fix them up. Thanks.

**Comment by pzim** [comment]
fixed documentation in 21fa7a3
