### ISSUE TITLE
If you dont have a :ref for a module in the Puppetfile then you get an empty Puppetfile

### ISSUE THREAD

**Issue by timhughes** [pzim/reaktor#28]
As per issue #7 reaktor requires a  :ref for a module in the Puppetfile. 

gsub!(pattern, replacement) will return `nil` if it doesn't find a substitution. see http://ruby-doc.org/core-2.1.4/String.html#method-i-gsub-21

Therefore, if you don't match `regex` correctly the value for `new_contents` becomes `nil` and that is passed as `contents` to `write_new_puppetfile(contents)`  and you end up with an empty Puppetfile. 

 https://github.com/pzim/reaktor/blob/master/lib/reaktor/r10k/puppetfile.rb
```
    # update the module ref in Puppetfile
    #
    # @param module_name - The module to change the ref for
    # @param branchname - The ref to change for the module
    def update_module_ref(module_name, branchname)
      pfile = loadFile
      regex = /(#{module_name}(\.git)+['"],)+(\s*):ref\s*=>\s*['"](\w+|\w+\.\d+\.\d+)['"]/m
      new_contents = pfile.gsub!(regex, """\\1\\3:ref => '#{branchname}'""".strip)
    end
```

There needs to be some defensive code in here to exit the process if the `new_contents` is nil after `new_contents = pfile.gsub!(regex, """\\1\\3:ref => '#{branchname}'""".strip)`

I think something along the lines of:

```
    # update the module ref in Puppetfile
    #
    # @param module_name - The module to change the ref for
    # @param branchname - The ref to change for the module
    def update_module_ref(module_name, branchname)
      pfile = loadFile
      regex = /(#{module_name}(\.git)+['"],)+(\s*):ref\s*=>\s*['"](\w+|\w+\.\d+\.\d+)['"]/m
      new_contents = pfile.gsub!(regex, """\\1\\3:ref => '#{branchname}'""".strip)
      if new_contents
        contents = new_contents
      else
        logger.info("In #{self} could not find module :ref for #{module_name} on #{branchname}")
        exit # I dont know if there needs to be any clean up code here or if `exit` is the correct method
      end
      contents
    end
```

**Comment by pzim** [comment]
I agree this should be a bit tighter. What really needs to happen is to re-establish the testing fixtures and add a test for this. I can look into that in the next few days. I appreciate your interest in helping improve the code and definitely welcome the help!
