### ISSUE TITLE
typo in reaktor-cfg.yml: daemonize

### ISSUE THREAD

**Issue by ChristianHirsch** [pzim/reaktor#36]
.. instead of deamonize.

**Comment by potto007** [comment]
Daemonize is correct - daemon is what we call it in *nix systems. https://en.wikipedia.org/wiki/Daemon_(computing)

**Comment by ChristianHirsch** [comment]
As far as I remember there was a mismatch between the daemonize in the config file and in some source code. That's why setting it in the config file had no effect. But I don't know if this is still an issue..
