### ISSUE TITLE
Puppetfile::update_module_ref assumes that a :ref already exist in Puppetfile

### ISSUE THREAD

**Issue by tremblaysimon** [pzim/reaktor#7]
At first glance it's not mandatory to supply a :ref for a module in the R10K Puppetfile. 

For now reaktor seems to work well only if a :ref has been specified. 

It's not a big issue and the workaround is simple since we only have to add a :ref to all module in the R10K Puppetfile and the regex will work as expected.

**Comment by pzim** [comment]
@tremblaysimon - is this still an ongoing problem for you? If not, I can close this out.

**Comment by tremblaysimon** [comment]
Yes we can close that.
